"""Added shifts

Revision ID: bcd9e435e123
Revises: 
Create Date: 2025-01-04 21:30:20.277909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd9e435e123'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('approx_end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index('ix_User_email')
        batch_op.create_index(batch_op.f('ix_User_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_email'))
        batch_op.create_index('ix_User_email', ['email'], unique=False)

    op.drop_table('shifts')
    # ### end Alembic commands ###
